'use strict';
(function(){
const st=document.createElement('style');st.textContent=".tut{position:fixed;left:0;right:0;bottom:0;z-index:50;padding:12px;pointer-events:none}.tutcard{pointer-events:auto;max-width:560px;margin:auto;background:#10142b;border:2px solid var(--amber);border-radius:6px;padding:14px 16px;box-shadow:0 0 0 4px #0008,0 0 24px #ffd07844;position:relative;overflow:hidden}.tutcard:after{content:\"\";pointer-events:none;position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#0002 3px 4px)}.tutcard h2{color:var(--amber);font-size:16px;margin:4px 0 6px}.tutcard p{font-size:13px;color:var(--ink)}.tutbar{display:flex;gap:8px;margin-top:12px;align-items:center;flex-wrap:wrap;position:relative;z-index:1}.tutbar button{min-height:44px}.tutbar .skip{margin-left:auto;background:none;border-color:transparent;color:var(--muted);text-decoration:underline}.tutstep{font-size:11px;letter-spacing:2px;color:var(--green)}.tutdots{display:flex;gap:5px;margin-top:8px}.tutdots i{width:14px;height:6px;background:#374056}.tutdots i.on{background:var(--amber)}.tuthl{outline:3px dashed var(--amber)!important;outline-offset:4px;scroll-margin-top:12px}";document.head.appendChild(st);
const h=document.createElement('div');h.innerHTML="<div class=\"tut\" id=\"tut\" hidden><div class=\"tutcard\" role=\"dialog\" aria-labelledby=\"tuttitle\" aria-live=\"polite\"><span class=\"tutstep\" id=\"tutstep\"></span><h2 id=\"tuttitle\"></h2><p id=\"tuttext\"></p><div class=\"tutdots\" id=\"tutdots\"></div><div class=\"tutbar\"><button id=\"tutprev\">\u2190 Atr\u00e1s</button><button class=\"primary\" id=\"tutnext\">Siguiente \u2192</button><button class=\"skip\" id=\"tutskip\">Saltar tutorial</button></div></div></div>";document.body.appendChild(h.firstChild);
const b=document.createElement('button');b.id='tutbtn';b.textContent='? Tutorial';const demo=document.getElementById('demo');demo.parentNode.insertBefore(b,demo);

const TUT_KEY='dragon-tutorial.v1',tutSteps=[
{t:'Bienvenido, caballero',x:'Tu misión: convertir recursos dispersos en conocimiento ordenado. A medida que describas, clasifiques y conectes, el dragón se encoge. Este tutorial dura un minuto y puedes saltarlo.',el:'view-scene',tab:'index'},
{t:'Índice de domesticación',x:'Mide cuánto has organizado: título, autoría y repositorio; disciplina y etiquetas; y una conexión con otro recurso. Es orden, no calidad científica.',el:'percent-panel',tab:'index'},
{t:'Empieza con un recurso',x:'Pulsa "+ Recurso" para añadir un artículo, dataset o citación. Si prefieres practicar, "Cargar ejemplo ficticio" carga datos inventados.',el:'toolbar',tab:'index'},
{t:'1 · Indexar',x:'Rellena la ficha: título, autoría y repositorio son obligatorios. Añade disciplina y etiquetas, y guarda. Cada ficha completa suma progreso. Usa la búsqueda y el filtro para encontrar silos.',el:'view-index',tab:'index'},
{t:'2 · Taxonomía',x:'Aquí se construye el atlas con tus disciplinas y etiquetas. Pulsa una disciplina para ver sus recursos y detecta lo que queda sin clasificar.',el:'tab-taxonomy',tab:'taxonomy'},
{t:'3 · Mapa de conocimiento',x:'En cada ficha puedes conectar un recurso con otro (cita, usa datos de, relacionado) y anotar la evidencia. Las líneas del mapa son tus conexiones; los nodos aislados siguen siendo silos. Pulsa un nodo para editarlo.',el:'tab-network',tab:'network'},
{t:'Guarda tus datos',x:'Todo se guarda solo en este navegador. Exporta JSON como copia de seguridad (se puede reimportar) o CSV para otras herramientas. Puedes reabrir este tutorial con "? Tutorial".',el:'toolbar',tab:'index'}];
let tutI=0,tutHL=null;
function tutTarget(k){return k==='view-scene'?document.querySelector('.hero .panel'):k==='percent-panel'?document.querySelector('.hero .panel.padded'):k==='toolbar'?document.querySelector('.toolbar'):k==='view-index'?$('view-index'):k==='tab-taxonomy'?document.querySelector('[data-tab=taxonomy]'):document.querySelector('[data-tab=network]')}
function tutShow(i){tutI=i;const st=tutSteps[i];tab(st.tab);if(tutHL)tutHL.classList.remove('tuthl');tutHL=tutTarget(st.el);if(tutHL){tutHL.classList.add('tuthl');tutHL.scrollIntoView({block:'start',behavior:'auto'})}$('tutstep').textContent='PASO '+(i+1)+' DE '+tutSteps.length;$('tuttitle').textContent=st.t;$('tuttext').textContent=st.x;$('tutdots').innerHTML=tutSteps.map((_,j)=>'<i class="'+(j===i?'on':'')+'"></i>').join('');$('tutprev').disabled=i===0;$('tutnext').textContent=i===tutSteps.length-1?'¡A por el dragón!':'Siguiente →';$('tutnext').focus({preventScroll:true})}
function tutOpen(){$('tut').hidden=false;document.body.style.paddingBottom='260px';tutShow(0)}
function tutClose(){$('tut').hidden=true;document.body.style.paddingBottom='';if(tutHL)tutHL.classList.remove('tuthl');tutHL=null;tab('index');window.scrollTo(0,0);try{localStorage.setItem(TUT_KEY,'1')}catch(e){}$('tutbtn').focus({preventScroll:true})}
$('tutbtn').onclick=tutOpen;$('tutskip').onclick=tutClose;$('tutprev').onclick=()=>tutShow(Math.max(0,tutI-1));$('tutnext').onclick=()=>tutI>=tutSteps.length-1?tutClose():tutShow(tutI+1);
document.addEventListener('keydown',e=>{if(!$('tut').hidden&&e.key==='Escape')tutClose()});
try{if(!localStorage.getItem(TUT_KEY))tutOpen()}catch(e){}

})();
